### ISSUE TITLE
logs ended with .gz

### ISSUE THREAD

**Issue by themakunga** [fei6409/log-highlight.nvim#3]
Hi, 

I have some issues trying to read logs that some instances that rotates, the logs are something like this,

`web.stdout.log1700000.gz`

**Comment by tan-wei** [comment]
It seems that it is not the function the plugin should provide.

**Comment by themakunga** [comment]
I can still read the logs but without highlight. Is similar to the #2 issue

**Comment by tan-wei** [comment]
Got it, I think you could define patterns to tell the filetype is `log` file just like #2 does.

**Comment by themakunga** [comment]
I fix it with this pattern

```lua
pattern = {
  ".*%.log%..*",
  ".*%.log%d+",
  ".*%.log%d+%.?gz?",
},
```
